"""
Company Discovery Agent.

Identifies COMPANIES (never job postings) matching the ICP. Seeds from two
sources: (1) companies surfaced by Market Trigger, validated/expanded with
a targeted search per company, and (2) a direct ICP-driven search (e.g.
"technology companies hiring backend engineers 100+ employees United
States") to catch companies that are hiring steadily without a recent
news-worthy trigger event — staffing demand isn't only generated by
funding rounds.

Per the spec: ignores job boards as the primary result, prefers Greenhouse/
Lever/Ashby/LinkedIn/Crunchbase/company sites (enforced by
core.search.SearchClient.search_primary_sources).
"""

from __future__ import annotations

from agents.base import agent_node
from core.llm import LLMClient
from core.memory import mark_discovered
from core.search import SearchClient
from core.state import State, company_key

EXTRACTION_SYSTEM_PROMPT = """You are identifying COMPANIES (not job \
listings, not articles) from web search results, for a staffing sales \
prospecting tool. The final entity must always be a company.

Given raw search results, extract distinct companies with whatever \
firmographic detail is actually present in the text. Do not invent a \
website, headquarters, or employee count that isn't supported by the text \
— use null instead.

Return JSON of the form:
{
  "companies": [
    {
      "name": "string",
      "website": "string or null - the company's main domain, not a job board URL",
      "industry": "string or null",
      "headquarters": "string or null - city, state/country",
      "employee_estimate": "string or null - e.g. '500-1000' or '1000+', as stated or implied",
      "linkedin_company_url": "string or null",
      "source_url": "the URL this was found on"
    }
  ]
}
"""


@agent_node("company_discovery")
def company_discovery_agent(state: State) -> dict:
    config = state.get("config", {})
    industry = config.get("industry", "Technology")
    icp = config.get("icp", {})
    locations = ", ".join(icp.get("locations", ["United States"]))
    focus = ", ".join(icp.get("hiring_focus", []))
    employee_min = icp.get("employee_size_min", 100)
    max_companies = config.get("max_companies", 15)

    search = SearchClient()
    llm = LLMClient()

    # Seed query directly from ICP, independent of triggers.
    icp_queries = [
        f"{industry} companies hiring {focus} {employee_min}+ employees {locations}",
        f"{industry} companies careers page open roles {focus} {locations}",
    ]

    # Also pull in company names already surfaced by Market Trigger, and
    # run one targeted lookup per company to get firmographic detail —
    # this is where Discovery "expands" a trigger into an actual company
    # record rather than just trusting the trigger agent's raw text.
    trigger_companies = sorted({t.get("company", "").strip() for t in state.get("triggers", []) if t.get("company")})

    all_results = []
    for q in icp_queries:
        all_results.extend(
            search.search_primary_sources(q, max_results=8, search_depth=config.get("search_depth", "basic"))
        )

    for name in trigger_companies[:max_companies]:
        all_results.extend(
            search.search_primary_sources(
                f'"{name}" careers company website headquarters employees',
                max_results=4,
                search_depth=config.get("search_depth", "basic"),
            )
        )

    if not all_results:
        return {"discovered_companies": state.get("discovered_companies", []), "_summary": "Company Discovery: no results found"}

    combined_text = "\n\n".join(
        f"URL: {r['url']}\nTITLE: {r['title']}\nCONTENT: {r['content'][:500]}" for r in all_results[:30]
    )

    extracted = llm.extract_json(EXTRACTION_SYSTEM_PROMPT, combined_text, max_tokens=3000)
    companies = extracted.get("companies", []) if extracted else []

    existing = list(state.get("discovered_companies", []))
    existing_keys = {c["key"] for c in existing}
    memory_update: dict = {}

    added = 0
    for c in companies:
        if added >= max_companies:
            break
        name = c.get("name", "").strip()
        if not name:
            continue
        website = c.get("website")
        key = company_key(name, website)
        if key in existing_keys:
            continue  # dedup — never process the same company twice
        record = {**c, "key": key, "name": name}
        existing.append(record)
        existing_keys.add(key)
        memory_update.update(mark_discovered(state, key, record))
        added += 1

    return {
        "discovered_companies": existing,
        **memory_update,
        "_summary": f"Company Discovery: added {added} new companies (total {len(existing)})",
    }
